sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm install -g cypress-cli
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm start &
  - cypress ci
  - npm install -g now-pipeline@1.4.0
  - now-pipeline --test "CYPRESS_HOST=$NOW_URL cypress ci" package.json src/*.js src/render/*.js
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
